name: Code Deploy
on:
  pull_request:
    branches: ["master"]
    types:
      - closed

jobs:
  deployit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: GHACTIONS
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_CODEDEPLOY }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Trigger a CodeDeploy deployment
        run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name Expander --deployment-group-name Default --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
