name: Run Pester Tests
on: [push]
jobs:
    test_run:
        name: Test run
        runs-on: ubuntu-latest
        steps:
            - name: test module
              id: test_module
              uses: ./
              shell: pwsh
              run: |
                  ./runtests.ps1
